### ISSUE TITLE
Experimental Setup 

### ISSUE THREAD

**Issue by pavaris-pm** [pavaris-pm/SpatialAttGanX#1]
## Greetings all contributors 💯 

Hmmmm. It seems like to make the model can interact with disentangled features, a need of attribute features in latent space is needed in order to make the model can be conditioned, with that, i've got some idea 💡 

### Here is a few steps that need to be taken before beginning an experiment. 

1.) download 2 main data from the given [link](https://mmlab.ie.cuhk.edu.hk/projects/CelebA.html), where the file name that need to be downloaded are as follows. Note here that all of them are in `downloads` section:
   - 1.1) **Align&Cropped Images (ZIP folder)**
   - 1.2) **Attributes Annotations (txt file)**

2.) After obtained these files, please kindly add to this repo and made a PR
3.) if step 1) and 2) completed. Let's begin our experiment !

Thank you in advance krub.

**Comment by pavaris-pm** [comment]
@supermind-c Can you please add more data into my drive by download the pretrained models (download from http://bit.ly/sagan-results) and upload that zip file into my drive

**Comment by supermind-c** [comment]
Hi, @pavaris-pm I have uploaded the files as per your request.

**Comment by pavaris-pm** [comment]
> Hi, @pavaris-pm I have uploaded the files as per your request. 
> 
> 

Thanks for your contribution krub. That's much helped !

**Comment by pavaris-pm** [comment]
@supermind-c  I've interested in experimenting with another cutting-edge pretrained model in this task. Can you please load all of the data in this [link](https://hkustgz-my.sharepoint.com/personal/haowang_hkust-gz_edu_cn/_layouts/15/onedrive.aspx?id=%2Fpersonal%2Fhaowang%5Fhkust%2Dgz%5Fedu%5Fcn%2FDocuments%2FNTU%20files%2Fprojects%2FByteDance%2Fface%20editing%2Fpretrained&ga=1) , and upload it again into my drive please.
